version: '3'
services:
  mysql:
    image : mysql:5.7.20
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  security:
    image: djkdeveloper/spring_boot_security
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_SCHEMA=security
    links:
      - mysql
